### register
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "name":"adi",
    "email":"adiirwn10@mail.com",
    "password":"adi123123"
}

### login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email":"adiirwn10@mail.com",
    "password":"adi123123"
}

### whoami
GET http://localhost:3000/api/v1/whoami
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkaSIsImVtYWlsIjoiYWRpaXJ3bjEwQG1haWwuY29tIiwiaXNfdmVyaWZpZWQiOnRydWUsImlhdCI6MTcxNTc4MDc2M30.zMzhWolI2efs4dclAW0_91AGFsxov_1p9gSxCyDSc5c

### request verify email
GET http://localhost:3000/api/v1/request-verify
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkaSIsImVtYWlsIjoiYWRpaXJ3bjEwQG1haWwuY29tIiwiaXNfdmVyaWZpZWQiOmZhbHNlLCJpYXQiOjE3MTU3ODA2Nzh9.jU2bR1UWiIFxedp1B9ou_jfvm4MloCut6yeGUI9_yi8