### register
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "name":"Tina",
    "email":"tinafina941@gmail.com",
    "password":"tina123"
}

### login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email":"tinafina941@gmail.com",
    "password":"tina123"
}

### whoami
GET http://localhost:3000/api/v1/whoami
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlRpbmEiLCJlbWFpbCI6InRpbmFmaW5hOTQxQGdtYWlsLmNvbSIsImlzX3ZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNzE1ODEzMjgzfQ.y5_YOArQsyu_KGO6r9jmjW4dyevlHwSei4owLDIiHtU

### request verify email
GET http://localhost:3000/api/v1/request-verify
# Authorization: Bearer tokentoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlRpbmEiLCJlbWFpbCI6InRpbmFmaW5hOTQxQGdtYWlsLmNvbSIsImlzX3ZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNzE1ODEzMjgzfQ.y5_YOArQsyu_KGO6r9jmjW4dyevlHwSei4owLDIiHtU